# -*- coding: utf-8 -*-
# :Project:   pycov-mode —
# :Created:   mer 8 dic 2021, 11:48:44
# :Author:    Lele Gaifax <lele@etour.tn.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2021 Lele Gaifax
#

check:
	coverage run -m pytest
	coverage json -o coverage.json
